### ISSUE TITLE
Make ArangoDB blueprints implementation improvements

### ISSUE THREAD

**Issue by eugene-kamenev** [ArangoDB-Community/tinkerpop-arangodb-provider#19]
Guys I wrote a tweet about my disappointment  to create entity mapper for arangodb.
Previously i wrote ![entity mapper for OrientDB](https://github.com/eugene-kamenev/orientdb-groovy), and it works fine and it was very easy to write it.
I decided to write for arangodb also, and experienced difficulties.

The idea I am following, is to wrap vertices and edges with an entity class, and call entity instance setters and getters directly on vertex/edge.

Lets see example class that i have for OrientDB:

``` groovy
public class User {
    private Town town;
    public final OrientVertex vertex;

    public User() {
        this.vertex = OrientBaseGraph.getActiveGraph().addTemporaryVertex("User", new Object[0]);
    }

    public User(final OrientVertex vertex) {
            this.vertex = vertex;
    }

    public User(final OIdentifiable oIdentifiable) {
        this.vertex = OrientBaseGraph.getActiveGraph().getVertex((Object)oIdentifiable);
    }

    public Country getCountry() {
        return this.getTown().getCountry();
    }

    public void setProfile(final Profile profile) {
        this.vertex.setProperty("profile", (Object)profile.vertex, OType.LINK);
    }

    public Town getTown() {
        return (Town) OrientGraphHelper.transformVertexToEntity((Class)Town.class, (OIdentifiable) this.vertex.getProperty("town"));
    }

    public void setTown(final Town town) {
        this.vertex.setProperty("town", (Object)town.vertex, OType.LINK);
    }
}
```

  Take a look at User class constructors. I can add temporaryVertex. If i add vertex in arangodb it is persisted into db. There is a lack of transaction support also. OrientDB blueprints implementation supports multiple transactions and isolation between nested transactions.
Also there is getActiveGraph() static method that will return OrientGraph instance if it was constructed somewhere before. Not a problem with arangodb in this case, but I think you can add this also.
Also I found that ArangoDBGraph constructor takes only one vertex collection name and only one edge. I cant understand why we cant create one graph for all database collections. I am not sure I can understand how to use ArangoDBGraph with multiple collections and edges.
And I have another question, in orientdb they have interface OIdentifiable that is implemented both by blueprints implementation Vertex/Edge and OrientDB native ODocument. So i am having a problem here also, with converting and casting objects.

Thanks, hope explanation was clear.

**Comment by fceller** [comment]
@eugene-kamenev thanks for detail explanation. I'll try to collect the information ASAP.

**Comment by eugene-kamenev** [comment]
@fceller still no news?

**Comment by fceller** [comment]
My colleague @a-brandt will be back on Friday. Hope he can help.

**Comment by fceller** [comment]
@eugene-kamenev I talked to my colleague Achim. There are some points we want to discuss. The Java driver for ArangoDB supports all the necessary features to (a) map documents to Java classes and (b) execute Graph queries. Did you have a look at the driver?

https://github.com/arangodb/arangodb-java-driver/blob/master/src/test/java/com/arangodb/example/ExecuteDocumentQueryExample.java

The blueprints driver follows the idea of having properties at edges and vertices. The Java driver on the other hand can easily be used to create an object-mapping because is using Google's Gson library (https://github.com/google/gson) which is very flexible. The driver also supports AQL queries, which can any do any Graph query.

It also leaves you the choice to model joins either by using graphs or (in case of 1-1 or 1-n) use links or arrays of links.

**Comment by arcanefoam** [comment]
I think the entity mapping is now addressed by VelociPack, not sure how this affects how Tinkerpop works.
Closing this as the code base and versions supported have changed significantly. Please reopen if you continue to experience this issue.
